#ifndef APP_CONFIG_C501_CHECKERS
#define APP_CONFIG_C501_CHECKERS

#define PROG_FULL_NAME "C501 Checkers"
#define PROG_FULL_NAME_GETTEXT _("C501 Checkers")

#define PROG_PKG_NAME "c501checkers"
#define PROG_PKG_NAME_GETTEXT _T(PROG_PKG_NAME)

#endif //APP_CONFIG_C501_CHECKERS
